#delimit;
clear;
pause off;
/*MIN-yang's bit to connect to oracle and set up home directory */  
cd "/home/mlee/Documents/projects/spacepanels/scallop/spatial_project_aug29";
quietly do "/home/mlee/Documents/Workspace/technical folder/do file scraps/odbc_connection_macros.do";
global oracle_cxn "conn("$mysole_conn") lower";


/* GLOBALS to set up YEARS and OTHER STUFF  
These will get passed to the other do files.*/
global firstyr=1996; 
global lastyr=2014; 
timer clear;


quietly forvalues yr=$firstyr/$lastyr{ ;
	tempfile new;
	local NEWfiles `"`NEWfiles'"`new'" "'  ;
	clear;
	odbc load, exec("select distinct t.state1, t.portlnd1 from veslog`yr's s, veslog`yr't t 
		where t.tripid= s.tripid 
			and s.qtykept>=1;")  $oracle_cxn;
	gen dbyear=`yr';
	quietly save `new';
};
dsconcat `NEWfiles';
replace portlnd1=subinstr(portlnd1," ","",.);
replace state1=subinstr(state1," ","",.);
tempfile t2 t9;
save `t9'; 
dups portlnd1 state1, drop terse;
save `t2';

use "/home/mlee/Documents/projects/spacepanels/port data/Ports_background_Info/communities_cleaned2.dta", clear;
replace portlnd1=subinstr(portlnd1," ","",.);
replace state1=subinstr(state1," ","",.);
dups, drop terse;
drop _expand;
tempfile t3;
save `t3';

use `t2', clear;
merge 1:1 portlnd1 state1 using `t3', keep(1 3);
pause;

keep statefp-namelsad;

gen mark=1;
dups, drop terse;
mdesc;
drop if geoid==.;
drop _expand;
notes drop _dta;
notes: This was generated by finding all of the portlnd1 & state1's in VESLOGyyyyT that had at least 1lb of fish landed (from VESLOGyyyyS);
notes: I used 1996-2014.;
notes: this was matched to the communities_cleaned2.dta file.  Only matches were retained.;
notes: then only the "spatial" data from census was retained. I generated a "mark"=1 value, because it's sometimes useful.;

format geoid %010.0f;
save "/home/mlee/Documents/projects/spacepanels/port data/Ports_background_Info/universe_of_ports.dta", replace;
/* Export the GEOID and MARK column to a csv.  REMEMBER TO MAKE A CSVT (CSV Template file) and put it in that directory for QGIS */
outsheet geoid mark using "/home/mlee/Desktop/spatial folder/scallop project/universe_of_ports.csv", comma replace ;

use `t9', clear;

